import { ArrowRight, CheckCircle2, Clock3, Globe2, HeartPulse, LockKeyhole, MapPin, Menu, Radio, ShieldCheck, Siren, UsersRound, X } from "lucide-react";
import { useState } from "react";
import { startLogin } from "@/const";

const pillars = [
  { icon: Siren, title: "One clear report", text: "Structured incident details help response teams understand what is happening faster." },
  { icon: MapPin, title: "Location with consent", text: "Share a landmark or device location so authorized responders know where to go." },
  { icon: Radio, title: "A connected response", text: "Keep the report, the status trail, and the response team in one secure thread." },
];

const BEACON_IMAGE = "/ecr-response-beacon.png";

const steps = [
  ["01", "Report", "Choose the emergency type and tell ECR what is happening."],
  ["02", "Locate", "Confirm a landmark or share your device location when safe."],
  ["03", "Coordinate", "Authorized teams triage the report and route it to the right agency."],
  ["04", "Stay informed", "Track the response status without repeatedly calling for updates."],
];

export default function Home() {
  const [menuOpen, setMenuOpen] = useState(false);

  return (
    <div className="min-h-screen bg-[#f5f8f7] text-slate-950">
      <header className="sticky top-0 z-40 border-b border-white/70 bg-white/80 backdrop-blur-2xl">
        <div className="mx-auto flex max-w-7xl items-center justify-between px-4 py-4 sm:px-6 lg:px-8">
          <a href="/" className="flex items-center gap-3" aria-label="ECR home">
            <span className="grid h-10 w-10 place-items-center rounded-2xl bg-[#063f3d] text-white shadow-lg shadow-emerald-950/10"><ShieldCheck size={21} /></span>
            <span><span className="block text-[15px] font-black tracking-[0.18em] text-[#063f3d]">ECR</span><span className="block text-[10px] font-semibold uppercase tracking-[0.14em] text-slate-400">Emergency Community Response</span></span>
          </a>
          <nav className="hidden items-center gap-7 text-sm font-bold text-slate-500 md:flex" aria-label="Main navigation">
            <a href="#how-it-works" className="transition hover:text-emerald-700">How it works</a>
            <a href="#network" className="transition hover:text-emerald-700">Response network</a>
            <a href="#trust" className="transition hover:text-emerald-700">Safety & privacy</a>
          </nav>
          <div className="hidden items-center gap-2 md:flex"><a href="/app" className="rounded-full px-4 py-2 text-xs font-black text-slate-600 hover:bg-slate-100">Open app</a><button onClick={() => startLogin()} className="rounded-full bg-[#063f3d] px-4 py-2 text-xs font-black text-white shadow-lg shadow-emerald-950/10 hover:-translate-y-0.5 hover:bg-[#075b55]">Sign in</button></div>
          <button className="rounded-xl p-2 text-slate-600 md:hidden" onClick={() => setMenuOpen(value => !value)} aria-label={menuOpen ? "Close menu" : "Open menu"}>{menuOpen ? <X size={22} /> : <Menu size={22} />}</button>
        </div>
        {menuOpen && <div className="border-t border-slate-100 bg-white px-4 py-4 md:hidden"><div className="grid gap-2 text-sm font-bold text-slate-600"><a href="#how-it-works" onClick={() => setMenuOpen(false)} className="rounded-xl px-3 py-2 hover:bg-slate-50">How it works</a><a href="#network" onClick={() => setMenuOpen(false)} className="rounded-xl px-3 py-2 hover:bg-slate-50">Response network</a><a href="#trust" onClick={() => setMenuOpen(false)} className="rounded-xl px-3 py-2 hover:bg-slate-50">Safety & privacy</a><a href="/app" className="rounded-xl bg-emerald-50 px-3 py-2 text-emerald-800">Open reporting app</a></div></div>}
      </header>

      <main>
        <section className="hero-surface relative overflow-hidden bg-[#063f3d]">
          <div className="hero-grid absolute inset-0 opacity-40" />
          <div className="absolute -right-24 -top-32 h-[28rem] w-[28rem] rounded-full bg-emerald-300/15 blur-3xl" />
          <div className="absolute bottom-0 left-1/3 h-72 w-72 rounded-full bg-cyan-300/10 blur-3xl" />
          <div className="relative mx-auto grid max-w-7xl gap-12 px-4 py-16 sm:px-6 lg:grid-cols-[1.05fr_0.95fr] lg:items-center lg:px-8 lg:py-24">
            <div className="reveal-up"><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/10 px-3 py-1.5 text-[11px] font-black uppercase tracking-[0.16em] text-emerald-100"><span className="h-2 w-2 animate-pulse rounded-full bg-emerald-300" /> Built for safer communities</div><h1 className="max-w-3xl text-5xl font-black leading-[0.98] tracking-[-0.05em] text-white sm:text-7xl">A clearer path from <span className="text-emerald-300">emergency</span> to help.</h1><p className="mt-6 max-w-xl text-base leading-7 text-emerald-50/75 sm:text-lg">ECR connects people who need help with authorized response teams, local agencies, and community responders through one trusted response loop.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><a href="/app" className="inline-flex h-13 items-center justify-center gap-2 rounded-2xl bg-[#13b981] px-6 text-sm font-black text-[#022c2b] shadow-xl shadow-emerald-950/20 hover:-translate-y-1 hover:bg-[#34d399]">Open reporting app <ArrowRight size={17} /></a><a href="tel:112" className="inline-flex h-13 items-center justify-center gap-2 rounded-2xl border border-white/15 bg-white/10 px-6 text-sm font-black text-white hover:-translate-y-1 hover:bg-white/15"><Radio size={17} /> Call 112</a></div><div className="mt-8 flex flex-wrap gap-x-6 gap-y-3 text-xs font-semibold text-emerald-100/65"><span className="inline-flex items-center gap-2"><LockKeyhole size={14} /> Private by design</span><span className="inline-flex items-center gap-2"><Globe2 size={14} /> Built for Nigeria</span><span className="inline-flex items-center gap-2"><CheckCircle2 size={14} /> Human-led response</span></div></div>
            <div className="relative min-h-[420px]"><div className="beacon-halo absolute right-4 top-1/2 h-72 w-72 -translate-y-1/2 rounded-full border border-emerald-200/20" /><div className="glass-card relative z-10 rounded-[2rem] border border-white/20 bg-white/10 p-3 shadow-2xl shadow-black/20 backdrop-blur-2xl"><div className="rounded-[1.5rem] bg-[#f4faf8]/95 p-6 shadow-inner shadow-white sm:p-8 sm:pr-40"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-emerald-700">The ECR promise</p><h2 className="mt-2 text-2xl font-black leading-tight text-slate-950">Fast enough for the moment. Thoughtful enough for the person.</h2></div><span className="icon-orb grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-emerald-100 text-emerald-700"><HeartPulse size={22} /></span></div><div className="mt-8 grid gap-4">{pillars.map(({ icon: Icon, title, text }) => <div key={title} className="flex gap-4 rounded-2xl border border-emerald-100 bg-white/75 p-4"><span className="icon-orb grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-emerald-50 text-emerald-700"><Icon size={18} /></span><div><p className="text-sm font-black text-slate-900">{title}</p><p className="mt-1 text-xs leading-5 text-slate-500">{text}</p></div></div>)}</div></div></div><img src={BEACON_IMAGE} alt="3D glass response beacon" className="hero-beacon pointer-events-none absolute -right-10 bottom-0 z-20 h-52 w-52 object-contain drop-shadow-[0_30px_30px_rgba(0,0,0,0.28)] sm:-right-14 sm:h-64 sm:w-64" /><div className="glass-particle absolute -right-3 top-10 h-3 w-3 rounded-full bg-cyan-200/80" /><div className="glass-particle absolute -left-2 bottom-16 h-2 w-2 rounded-full bg-emerald-200/80 [animation-delay:900ms]" /></div>
          </div>
        </section>

        <section className="border-b border-slate-200/80 bg-white"><div className="mx-auto grid max-w-7xl gap-6 px-4 py-7 sm:grid-cols-3 sm:px-6 lg:px-8"><div><p className="text-3xl font-black text-[#063f3d]">24/7</p><p className="mt-1 text-xs font-bold uppercase tracking-[0.14em] text-slate-400">Response-ready mindset</p></div><div><p className="text-3xl font-black text-[#063f3d]">1 clear</p><p className="mt-1 text-xs font-bold uppercase tracking-[0.14em] text-slate-400">Report-to-resolution thread</p></div><div><p className="text-3xl font-black text-[#063f3d]">Local first</p><p className="mt-1 text-xs font-bold uppercase tracking-[0.14em] text-slate-400">Communities and agencies together</p></div></div></section>

        <section id="how-it-works" className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8 lg:py-24"><div className="max-w-2xl"><p className="text-xs font-black uppercase tracking-[0.18em] text-emerald-700">A simple response loop</p><h2 className="mt-3 text-3xl font-black tracking-tight text-slate-950 sm:text-5xl">Clarity when the situation is anything but clear.</h2><p className="mt-4 text-base leading-7 text-slate-500">ECR turns the first call for help into structured information that the right people can act on.</p></div><div className="mt-10 grid gap-4 md:grid-cols-4">{steps.map(([number, title, text], index) => <div key={number} className="glass-tile rounded-3xl border border-slate-200/80 bg-white/80 p-5"><span className={`grid h-10 w-10 place-items-center rounded-xl text-xs font-black ${index === 0 ? "bg-[#063f3d] text-white" : "bg-emerald-50 text-emerald-800"}`}>{number}</span><h3 className="mt-6 text-lg font-black">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{text}</p></div>)}</div></section>

        <section id="network" className="bg-[#eaf6f1]"><div className="mx-auto grid max-w-7xl gap-10 px-4 py-16 sm:px-6 lg:grid-cols-[0.9fr_1.1fr] lg:items-center lg:px-8 lg:py-24"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-emerald-700">A coordinated network</p><h2 className="mt-3 text-3xl font-black tracking-tight text-slate-950 sm:text-5xl">The right response should not depend on who you already know.</h2><p className="mt-5 text-base leading-7 text-slate-600">ECR is designed to route structured reports toward verified agencies, dispatch teams, and trained community responders while keeping access scoped and accountable.</p><a href="/app" className="mt-7 inline-flex items-center gap-2 rounded-xl bg-[#063f3d] px-5 py-3 text-sm font-black text-white hover:-translate-y-0.5 hover:bg-[#075b55]">Explore the reporting flow <ArrowRight size={16} /></a></div><div className="grid gap-4 sm:grid-cols-2"><div className="rounded-3xl border border-white/80 bg-white/75 p-6 shadow-sm"><UsersRound className="text-emerald-700" size={24} /><h3 className="mt-6 text-lg font-black">For communities</h3><p className="mt-2 text-sm leading-6 text-slate-500">Report safely, share only what is necessary, and stay informed as the status changes.</p></div><div className="rounded-3xl border border-white/80 bg-white/75 p-6 shadow-sm"><ShieldCheck className="text-emerald-700" size={24} /><h3 className="mt-6 text-lg font-black">For agencies</h3><p className="mt-2 text-sm leading-6 text-slate-500">Receive structured incident data, contact details, location context, and a traceable audit trail.</p></div><div className="rounded-3xl border border-white/80 bg-white/75 p-6 shadow-sm"><Clock3 className="text-emerald-700" size={24} /><h3 className="mt-6 text-lg font-black">For responders</h3><p className="mt-2 text-sm leading-6 text-slate-500">See the next action, accept ownership, and keep the person reporting close to the loop.</p></div><div className="rounded-3xl border border-white/80 bg-white/75 p-6 shadow-sm"><LockKeyhole className="text-emerald-700" size={24} /><h3 className="mt-6 text-lg font-black">For trust</h3><p className="mt-2 text-sm leading-6 text-slate-500">Role-based access, secure sessions, validation, audit events, and privacy-aware data handling.</p></div></div></div></section>

        <section id="trust" className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8 lg:py-24"><div className="rounded-[2rem] bg-[#063f3d] px-6 py-10 text-center shadow-2xl shadow-emerald-950/10 sm:px-10"><LockKeyhole className="mx-auto text-emerald-300" size={28} /><h2 className="mt-5 text-3xl font-black tracking-tight text-white sm:text-4xl">Safety is part of the product, not a footer note.</h2><p className="mx-auto mt-4 max-w-2xl text-sm leading-6 text-emerald-50/70">Share what is safe and necessary. For immediate danger, call official emergency services first. ECR helps create a clearer coordination trail around that response.</p><a href="/app" className="mt-7 inline-flex items-center gap-2 rounded-xl bg-[#13b981] px-5 py-3 text-sm font-black text-[#022c2b] hover:-translate-y-0.5 hover:bg-[#34d399]">Start a report <ArrowRight size={16} /></a></div></section>
      </main>

      <footer className="border-t border-slate-200 bg-white"><div className="mx-auto grid max-w-7xl gap-10 px-4 py-10 sm:px-6 md:grid-cols-[1.4fr_1fr_1fr] lg:px-8"><div><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#063f3d] text-white"><ShieldCheck size={18} /></span><span className="text-sm font-black tracking-[0.16em] text-[#063f3d]">ECR</span></div><p className="mt-4 max-w-sm text-sm leading-6 text-slate-500">Emergency Community Response — safer communities through clearer coordination.</p></div><div><p className="text-xs font-black uppercase tracking-[0.15em] text-slate-400">Explore</p><div className="mt-4 grid gap-3 text-sm font-bold text-slate-600"><a href="#how-it-works" className="hover:text-emerald-700">How it works</a><a href="#network" className="hover:text-emerald-700">Response network</a><a href="/app" className="hover:text-emerald-700">Open reporting app</a></div></div><div><p className="text-xs font-black uppercase tracking-[0.15em] text-slate-400">Important</p><div className="mt-4 grid gap-3 text-sm font-bold text-slate-600"><a href="tel:112" className="hover:text-emerald-700">Call 112</a><a href="#trust" className="hover:text-emerald-700">Safety & privacy</a><span className="inline-flex items-center gap-2 text-xs text-slate-400"><LockKeyhole size={13} /> Authorized access only</span></div></div></div><div className="border-t border-slate-100"><div className="mx-auto flex max-w-7xl flex-col gap-2 px-4 py-5 text-xs text-slate-400 sm:flex-row sm:items-center sm:justify-between sm:px-6 lg:px-8"><span>© 2026 Emergency Community Response</span><span>Do not delay calling official emergency services</span></div></div></footer>
    </div>
  );
}
